query {
  frenchWord(id: 1) {
    data {
      id
      attributes {
        Translation
        german_word {
          data {
            attributes {
              Word
            }
          }
        }
      }
    }
  }
}
