query {
  germanWord(id: 33) {
    data {
      id
      attributes {
        Word
        french_word {
          data {
            attributes {
              Translation
            }
          }
        }
        germansentences {
          data {
            attributes {
              Sentence
            }
          }
        }
        englishsentences {
          data {
            attributes {
              Sentence
            }
          }
        }
      }
    }
  }
}

Version avec Query variables :

query ($id:ID!) {
  germanWord(id: $id) {
    data {
      id
      attributes {
        Word
        french_word {data{attributes{Translation}}}
        germansentences {data{attributes{Sentence}}}
        englishsentences {data{attributes{Sentence}}}
      }
    }
  }
}

Query variables :

{
  "id": 33
}